### ISSUE TITLE
Is there any '.ckpt' format pretrained model on SALICON?

### ISSUE THREAD

**Issue by LJOVO** [alexanderkroner/saliency#12]
Dear authors,

I am trying to fine-tune the provided '.pd' format pretrained model but failed.
May I request a re-trainable '.ckpt' format pretrained model on SALICON?

Thanks!

**Comment by alexanderkroner** [comment]
Sure, I uploaded the `.ckpt` files for the SALICON version here:

- CPU: https://drive.google.com/file/d/1ZWRCKQyzjtT_D1HcxT-IXSlVfogB1uJw/view
- GPU: https://drive.google.com/file/d/1m9ZvZJXfBqOocAE81dgGMX7L049-oi2q/view

**Comment by LJOVO** [comment]
> Sure, I uploaded the `.ckpt` files for the SALICON version here:
> 
> * CPU: https://drive.google.com/file/d/1ZWRCKQyzjtT_D1HcxT-IXSlVfogB1uJw/view
> * GPU: https://drive.google.com/file/d/1m9ZvZJXfBqOocAE81dgGMX7L049-oi2q/view

Thank you vey much!
