### ISSUE TITLE
"tf.data" input pipeline dimensions?

### ISSUE THREAD

**Issue by Wmir** [alexanderkroner/saliency#16]
Hi Alexander,

Thank you for putting your code on github, it's really impressive and amazing work. I was going through your code however I have some confusion, if you could please help me out with that. 

My query is about creating data piplines using **"tf.data"**. I debug the code and got the final dataset structure as given below:

<DatasetV1Adapter shapes: ((?, ?, ?, 3), (?, ?, ?, 1), (?, 2), ((?,), (?,))), types: (tf.float32, tf.float32, tf.int32, (tf.string, tf.string))>

(?, ?, ?, 3):  Input Image
(?, ?, ?, 1):  Saliency map
(?, 2)       :  Please explain
((?,), (?,)) :  Please explain

Please if you can help me out by explaining the above two dimensions. I will deeply appreciate your help.

**Comment by alexanderkroner** [comment]
Hey, thank you for the kind words!

Indeed, the TF dataset structure consists of four parts. I'll explain each of them based on an example from the SALICON dataset:

- `(batch_size, height, width, channels)` is the first tensor representing the **input images**, e.g. as `(1, 240, 320, 3)`.
- `(batch_size, height, width, channels)` is the second tensor representing the **saliency maps**, e.g. as `(1, 240, 320, 1)`.
- `(original_height, original_width)` is the third element, which stores the **original sizes** for each image. I keep these values to resize predicted saliency maps to their original resolution after inference. In the case of SALICON, this would be `(480, 640)`.
- `(image_path, saliency_path)` is the last element, where the **paths** to the image files and saliency maps are stored. I only do this to keep track of the filename and save the predicted saliency maps with the same name after inference. For example, this would look like `(".../COCO_train2014_000000264888.jpg", ".../COCO_train2014_000000264888.png")`.

I hope these explanations helped. Let me know if anything is still unclear!

**Comment by Wmir** [comment]
Thanks for such a quick response and very well explained.
