### ISSUE TITLE
saliency metric evaluation on test dataset

### ISSUE THREAD

**Issue by shilpamathew14** [alexanderkroner/saliency#17]
Thank you Sir for the wonderful code you have made here... thoroughly worked and clearly coded.. 

Sir, i tried to train on salicon and tested on (say) osie dataset. The predicted saliency maps are obtained on the results folder perfectly. I would like to know  how i will be able to compute different saliency metric (say kld, AUC-Judd) between the predicted and true maps via code frame? How can I implement an evaluate function between them? It would be great if you can provide help towards this..

**Comment by EricPengShuai** [comment]
@shilpamathew14 Maybe you can try another github code: https://github.com/matthias-k/pysaliency, which can be found on [MIT saliency website](https://saliency.tuebingen.ai/evaluation.html).

**Comment by alexanderkroner** [comment]
Sorry for the late reply! To evaluate predicted saliency maps against the ground truth, I used this repository which implements commonly used metrics in MATLAB: https://github.com/cvzoya/saliency/tree/master/code_forMetrics

If you're looking for a solution in Python, I can also recommend the **pysaliency** package: https://github.com/matthias-k/pysaliency

**Comment by shilpamathew14** [comment]
Thanks a lot for the responses. I have been trying with pysaliency these days and it has been working good.... Thank you for the suggestions.
