### ISSUE TITLE
error while running demo with next version of Tensorflow

### ISSUE THREAD

**Issue by mehimanshupatil** [alexanderkroner/saliency#20]
I am trying to run demo with a tensorflow version 1.2.1 (next version from current 1.1.2) but in browser gives following error `tfjs@1.2.1:2 Uncaught (in promise) Error: The shape of dict['input'] provided in model.execute(dict) must be [], but was [1,48,64,3]`.

**Comment by alexanderkroner** [comment]
I was able to reproduce this error when upgrading the version of tfjs to 1.2.1. Unfortunately, I'm not familiar with the breaking changes between the two versions. I only tested the code for tfjs@1.1.2.

**Comment by mehimanshupatil** [comment]
ok what i found is
`loadGraphModel` function returns model which consist `inputs` 
with value  `[{ dtype: "float32",
name: "input",
shape: undefined }]` 
while in after updating tf it gives `[{ dtype: "float32",
name: "input",
shape: [] }]`

so there is a change in the `getTensorShapeParam` function in tfjs which returns `undefined` by default for shape while in latest version it returns `[]` 
 
 what I think is in model.json the item in the node key is
  ```
  {
             "name":"input",
             "op":"Placeholder",
             "attr":{
                "dtype":{
                   "type":"DT_FLOAT"
                },
                "shape":{"shape":  {} }
             }
          }
``` 
while it should be converted to 
```
  {
             "name":"input",
             "op":"Placeholder",
             "attr":{
                "dtype":{
                   "type":"DT_FLOAT"
                },
                "shape":{"shape": {"unknownRank": true}}
             }
          }
```

**Comment by alexanderkroner** [comment]
Thanks for providing the solution! I changed the `model.json` files as you suggested and the demo now runs with higher versions of tfjs as well.

**Comment by mehimanshupatil** [comment]
Great
