### ISSUE TITLE
Tensorflow v2.7

### ISSUE THREAD

**Issue by iboraham** [alexanderkroner/saliency#24]
Hi 

I'm trying to test your pretrained model on SALICON with my images. I used #15 this method to convert tf1 model to tf2 however, output seems not correct to me. 

Here is my code,

```python
import tensorflow as tf

imported = tf.saved_model.load("./converted_model")
imported = imported.signatures["serving_default"]

img = tf.io.read_file("face.jpg")
tensor = tf.io.decode_image(img, channels=3, dtype=tf.dtypes.float32)
#tensor = tf.image.resize(tensor, [240, 320])
input_tensor = tf.expand_dims(tensor, axis=0)
# input_tensor = tf.ones((1, 240, 320, 3))
saliency = imported(input_tensor)["output"]

tf.keras.preprocessing.image.save_img('face_out.jpg',saliency[0])
```

Here is the input image
![face](https://user-images.githubusercontent.com/58372366/174570125-517e82d7-f310-4b56-a9f5-922661767539.jpg)

Here is the output image
![face_out](https://user-images.githubusercontent.com/58372366/174570123-cc5175ca-5ba3-4e5f-abe4-1f98ee32f01b.jpg)

Thanks!

**Comment by alexanderkroner** [comment]
Hi! You see this incorrect output because the input to the model requires values in the range of [0, 255]. If you simply remove the `dtype` argument from the function `decode_image`, then this solves the issue! Another point you should consider is that the model ideally receives images of the size it was trained on. For the SALICON version, this is (240, 320).

```python
imported = tf.saved_model.load("./converted_model")
imported = imported.signatures["serving_default"]

img = tf.io.read_file("face.jpg")
tensor = tf.io.decode_image(img, channels=3)

inference_shape = (240, 320)
original_shape = tensor.shape[:2]

input_tensor = tf.expand_dims(tensor, axis=0)

input_tensor = tf.image.resize(input_tensor, inference_shape,
                               preserve_aspect_ratio=True)

saliency = imported(input_tensor)["output"]

saliency = tf.image.resize(saliency, original_shape)
```

**Comment by iboraham** [comment]
That worked, thanks a lot!
