### ISSUE TITLE
TF 2.0+ incompatibility (ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms')

### ISSUE THREAD

**Issue by gautamm20** [alexanderkroner/saliency#28]
TF 1.13 is quite outdated. TF 2.11 is the latest and does not support graphs. Any chance of updating the code or helping out on how this can work with newer TF versions?

**Comment by alexanderkroner** [comment]
Hi, I wrote some code [here](https://github.com/alexanderkroner/saliency/issues/15#issuecomment-865261948) that converts the trained models from TF1 to TF2 and allows you to generate saliency maps from images. I tested it with version `2.4.1` and it works well!
