### ISSUE TITLE
your demo's time

### ISSUE THREAD

**Issue by xuyangbit** [alexanderkroner/saliency#4]
Hello, what is the frame rate of the saliency detection video you provide, and how is the quality？
thank u~

**Comment by alexanderkroner** [comment]
Hey, the video was made with a resolution of 240x320px and ran at a frame rate of around 30fps. If you use the demo [here](https://storage.googleapis.com/msi-net/demo/index.html), then the frame rate depends on your hardware. The quality can be adjusted and ranges from 48x64px (very low) to 240x320px (very high).
