### ISSUE TITLE
Problem in experimental module

### ISSUE THREAD

**Issue by dibs06** [alexanderkroner/saliency#6]
After successfully download salicon it was showing error "tensorflow.data has no attribute  experimental
can you give me the solution?

**Comment by alexanderkroner** [comment]
This sounds like a version issue to me. Are you using tensorflow 1.13.1?

**Comment by dibs06** [comment]
I am using TensorFlow 1.9.0

**Comment by alexanderkroner** [comment]
In that case try to update your version to 1.13.1
This should solve the problem!
