### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by reshma1483** [alexanderkroner/saliency#9]
I have installed 
python 3.6 with keras(2.3.1) 
i tried uninstalling and reinstalling still I get the error 

could u please help me in this

**Comment by alexanderkroner** [comment]
Hey, did you try to install the package requirements listed [here](https://github.com/alexanderkroner/saliency#requirements)?
I only tested the code with tensorflow 1.13.1 and not keras.
